version: '3'

services:
  auth:
    build: .
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - APP_PORT=3000
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  redis:
